apiVersion: app.helios.io/v1alpha1
kind: HeliosApp
metadata:
  name: ktest1
  namespace: default
spec:

  description: "Managed by Helios Operator"
  owner: 
  
  # Required Git/Docker Info
  imageRepo: myuser/k-test1
  gitRepo: "https://github.com/PhamHoangKha1403/ktest1.git"
  gitopsRepo: https://github.com/PhamHoangKha1403/ktest1-gitops
  gitopsPath: "apps/ktest1" # Assumed path
  
  # Webhook Config
  webhookDomain: unarriving-unrapturously-amia.ngrok-free.dev
  webhookSecret: "github-credentials"
  gitopsSecretRef: "github-credentials"

  components:
    - name: ktest1-backend
      type: web-service
      properties:
        image: myuser/k-test1:latest
        port: 8080
        replicas: 1
        env:
          - name: NODE_ENV
            value: "production"
      traits:
        - type: service
          properties:
            port: 8080
            targetPort: 8080
