apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: ktest1-pipeline-run
  annotations:
    janus-idp.io/tekton: ktest1-service
spec:
  serviceAccountName: pipeline
  pipelineRef:
    name: from-code-to-cluster
  params:
  - name: image-repo
    value: index.docker.io/myuser/k-test1
  - name: app-repo-url
    value: https://github.com/PhamHoangKha1403/ktest1.git
  - name: app-repo-revision
    value: main
  - name: gitops-repo-url
    value: https://github.com/PhamHoangKha1403/ktest1-gitops
  - name: gitops-repo-branch
    value: main
  - name: manifest-path-in-gitops-repo
    value: ./deployment.yaml
  - name: docker-secret
    value: docker-credentials 
  workspaces:
  - name: source
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
